### PR TITLE
Log: add MDC getter

### PR DESCRIPTION
**Pull request by zarlen**
@k7d @skazhy @danielglauser, would like to provide rollbar with any MDC goodies.

### CODE REVIEW

**Comment by jentfoo** [comment]
The old airbrake MDC inclusions filtered out things like the EC2 api key, is there a need for that here?

**Comment by zarlen** [comment]
I would like to make these exclusions configurable, i.e. I'd like to have the entire MDC.

**Comment by k7d** [comment]
MDC is actually expected to be part of request value now:

https://github.com/fullcontact/full.contact/blob/master/src/fc/serverplus.clj#L121
https://github.com/fullcontact/full.monty/blob/master/full.http/src/full/http/server.clj#L136

So I would just use that. This MDC will probably not work because of multiple go block layers.

**Comment by skazhy** [comment]
> https://github.com/fullcontact/full.contact/blob/master/src/fc/serverplus.clj#L121
https://github.com/fullcontact/full.monty/blob/master/full.http/src/full/http/server.clj#L136

Friendly reminder: `full.contact` is not open source.

**Comment by skazhy** [comment]
+1 for Kaspars comment.

**Pull request closed without merging**
